version: '3'
services:
  app:  # ここが "app" である必要があります
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - "10000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
