version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:15
    container_name: product_management_db
    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: unless-stopped

  # PHPアプリケーション
  web:
    build: .
    container_name: product_management_web
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=product_management
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/nginx
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
