name: Manual PHPUnit

on:
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # push to the repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          extensions: mbstring, pdo, pdo_sqlite, pdo_mysql, pdo_pgsql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # デバッグ用ステップを追加
      - name: Debug - Show directory structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Directory structure ==="
          ls -la
          echo "=== Find ProductService.php ==="
          find . -name "ProductService.php" -type f
          echo "=== src directory structure ==="
          ls -la src/ || echo "src directory not found"
          echo "=== Check if vendor/autoload.php exists ==="
          ls -la vendor/autoload.php || echo "vendor/autoload.php not found"

      - name: Debug - Show composer.json
        run: |
          echo "=== composer.json content ==="
          cat composer.json

      - name: Debug - Show phpunit.xml
        run: |
          echo "=== phpunit.xml or phpunit.xml.dist content ==="
          cat phpunit.xml || cat phpunit.xml.dist || echo "No phpunit config found"

      - name: Debug - Check ProductService.php content
        run: |
          echo "=== ProductService.php location and content ==="
          find . -name "ProductService.php" -exec echo "Found at: {}" \; -exec head -10 {} \;

      - name: Debug - Check test file
        run: |
          echo "=== ProductServiceTest.php first 20 lines ==="
          head -20 test-code/tests/ProductServiceTest.php

      - name: Run PHPUnit with HTML coverage
        run: |
          mkdir -p test-code/result
          vendor/bin/phpunit --coverage-html test-code/result test-code/tests/ProductServiceTest.php

      - name: Commit and Push Coverage Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test-code/result/
          git commit -m "chore: Update PHPUnit coverage report [skip ci]" || echo "No changes to commit"
          git push origin main
          
