name: Manual PHPUnit

on:
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # push to the repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          extensions: mbstring, pdo, pdo_sqlite, pdo_mysql, pdo_pgsql

      # composer.jsonを修正してPHPUnitを追加
      - name: Update composer.json
        run: |
          cat > composer.json << 'EOF'
          {
              "autoload": {
                  "psr-4": {
                      "App\\": "src/"
                  }
              },
              "require-dev": {
                  "phpunit/phpunit": "^10.5"
              }
          }
          EOF

      # ディレクトリ名を修正
      - name: Fix directory name case
        run: |
          if [ -d "src/service" ]; then
            mv src/service src/Service
          fi

      # phpunit.xml.distを修正
      - name: Fix phpunit.xml.dist
        run: |
          cat > phpunit.xml.dist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <phpunit bootstrap="vendor/autoload.php"
                   colors="true"
                   stopOnFailure="false">
              <testsuites>
                  <testsuite name="App Test Suite">
                      <directory>test-code/tests</directory>
                  </testsuite>
              </testsuites>
              <coverage processUncoveredFiles="true">
                  <include>
                      <directory suffix=".php">src/Service</directory>
                  </include>
              </coverage>
          </phpunit>
          EOF

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit with HTML coverage
        run: |
          mkdir -p test-code/result
          vendor/bin/phpunit --coverage-html test-code/result test-code/tests/ProductServiceTest.php

      - name: Commit and Push Coverage Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test-code/result/
          git commit -m "chore: Update PHPUnit coverage report [skip ci]" || echo "No changes to commit"
          git push origin main
          
